# Build and deploy app to ftp server on develop push
name: CI

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: FTP deploy
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: "."
        remoteDir: "chillibits.com/pmapp"
    - name: Build request
      uses: fjogeleit/http-request-action@master
      with:
        url: 'https://www.chillibits.com/pmapp/src/build_test.php'
        method: 'GET'
        preventFailureOnNoResponse: 'true'